In [1]:
import pandas as pd
import pickle
from string import ascii_uppercase as alphabet

In [2]:
# extracting all tables in website
all_tables = pd.read_html('https://es.wikipedia.org/wiki/Copa_Mundial_Femenina_de_F%C3%BAtbol_de_2023')

15 - 22 - 29 - 36 - 43 - 50 - 57 - 64

In [3]:
all_tables[64]

          Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0       Alemania     0   0   0   0   0   0   0     0
1      Marruecos     0   0   0   0   0   0   0     0
2       Colombia     0   0   0   0   0   0   0     0
3  Corea del Sur     0   0   0   0   0   0   0     0

In [4]:
# A -> H
# 15 -> 7*8 + 15 = 71
all_tables = pd.read_html('https://es.wikipedia.org/wiki/Copa_Mundial_Femenina_de_F%C3%BAtbol_de_2023')
for i in range(15,71,7): # 11 18 25
    print(i)
    df = all_tables[i]
    #df.rename(columns={df.columns[1]:'Team'}, inplace=True)
    print(df)

15
          Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0  Nueva Zelanda     0   0   0   0   0   0   0     0
1        Noruega     0   0   0   0   0   0   0     0
2      Filipinas     0   0   0   0   0   0   0     0
3          Suiza     0   0   0   0   0   0   0     0
22
      Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0  Australia     0   0   0   0   0   0   0     0
1    Irlanda     0   0   0   0   0   0   0     0
2    Nigeria     0   0   0   0   0   0   0     0
3     Canadá     0   0   0   0   0   0   0     0
29
       Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0      España     0   0   0   0   0   0   0     0
1  Costa Rica     0   0   0   0   0   0   0     0
2      Zambia     0   0   0   0   0   0   0     0
3       Japón     0   0   0   0   0   0   0     0
36
       Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0  Inglaterra     0   0   0   0   0   0   0     0
1       Haití     0   0   0   0   0   0   0     0
2   Dinamarca     0   0   0   0   0   0   0     0
3       China     0   0   0   0   0   0   0     0
43
           Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0  Estados Unidos     0   0   0   0   0   0   0     0
1         Vietnam     0   0   0   0   0   0   0     0
2    Países Bajos     0   0   0   0   0   0   0     0
3        Portugal     0   0   0   0   0   0   0     0
50
    Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0  Francia     0   0   0   0   0   0   0     0
1  Jamaica     0   0   0   0   0   0   0     0
2   Brasil     0   0   0   0   0   0   0     0
3   Panamá     0   0   0   0   0   0   0     0
57
      Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0     Suecia     0   0   0   0   0   0   0     0
1  Sudáfrica     0   0   0   0   0   0   0     0
2     Italia     0   0   0   0   0   0   0     0
3  Argentina     0   0   0   0   0   0   0     0
64
          Equipo  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0       Alemania     0   0   0   0   0   0   0     0
1      Marruecos     0   0   0   0   0   0   0     0
2       Colombia     0   0   0   0   0   0   0     0
3  Corea del Sur     0   0   0   0   0   0   0     0

In [5]:
all_tables = pd.read_html('https://es.wikipedia.org/wiki/Copa_Mundial_Femenina_de_F%C3%BAtbol_de_2023')

dict_table = {}
for letter, i in zip(alphabet, range(15,71,7)): # A=15, B=22, ..., H=64
    df = all_tables[i]
    df.rename(columns={df.columns[0]:'Team'}, inplace=True)
    dict_table[f'{letter}'] = df

In [6]:
dict_table.keys()

dict_keys(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])

In [ ]:
dict_table['Group H']

            Team  Pts.  PJ  PG  PE  PP  GF  GC  Dif.
0       Alemania     0   0   0   0   0   0   0     0
1      Marruecos     0   0   0   0   0   0   0     0
2       Colombia     0   0   0   0   0   0   0     0
3  Corea del Sur     0   0   0   0   0   0   0     0

In [ ]:
with open('dict_table', 'wb') as output:
    pickle.dump(dict_table, output)